### ISSUE TITLE
Add function to access susi api service

### ISSUE THREAD

**Issue by djmgit** [loklak/loklak_nodejs_api#6]
Add a function to this library to access the susi api service.

**Comment by mariobehling** [comment]
Inhowfar should we mix SUSI and loklak? Shouldn't we have two separate APIs?

**Comment by mariobehling** [comment]
What is the use case?

**Comment by djmgit** [comment]
@mariobehling Actually I was going through the python api, I found that it contains function to access susi api (although it has got a problem https://github.com/loklak/loklak_python_api/pull/62 ). So I thought of adding a corresponding function to this library.

**Comment by mariobehling** [comment]
@djmgit If there is no specific use case the APIs do not need to be connected. Please open issues in the SUSI API Wrapper: https://github.com/fossasia/susi_api_wrapper

Currently we only have one common repository for all APIs. There is only a Python implementation anyways. SUSI and loklak are separated now. Closing this therefore.
